// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: proto/whirlpool/whirlpool.proto

package whirlpool

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenA string `protobuf:"bytes,1,opt,name=tokenA,proto3" json:"tokenA,omitempty"`
	TokenB string `protobuf:"bytes,2,opt,name=tokenB,proto3" json:"tokenB,omitempty"`
}

func (x *GetPriceRequest) Reset() {
	*x = GetPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_whirlpool_whirlpool_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceRequest) ProtoMessage() {}

func (x *GetPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whirlpool_whirlpool_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceRequest.ProtoReflect.Descriptor instead.
func (*GetPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_whirlpool_whirlpool_proto_rawDescGZIP(), []int{0}
}

func (x *GetPriceRequest) GetTokenA() string {
	if x != nil {
		return x.TokenA
	}
	return ""
}

func (x *GetPriceRequest) GetTokenB() string {
	if x != nil {
		return x.TokenB
	}
	return ""
}

type GetPriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetPriceResponse) Reset() {
	*x = GetPriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_whirlpool_whirlpool_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceResponse) ProtoMessage() {}

func (x *GetPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whirlpool_whirlpool_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceResponse.ProtoReflect.Descriptor instead.
func (*GetPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_whirlpool_whirlpool_proto_rawDescGZIP(), []int{1}
}

func (x *GetPriceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token0 string `protobuf:"bytes,1,opt,name=token0,proto3" json:"token0,omitempty"`
	Token1 string `protobuf:"bytes,2,opt,name=token1,proto3" json:"token1,omitempty"`
}

func (x *GetPairRequest) Reset() {
	*x = GetPairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_whirlpool_whirlpool_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairRequest) ProtoMessage() {}

func (x *GetPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whirlpool_whirlpool_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairRequest.ProtoReflect.Descriptor instead.
func (*GetPairRequest) Descriptor() ([]byte, []int) {
	return file_proto_whirlpool_whirlpool_proto_rawDescGZIP(), []int{2}
}

func (x *GetPairRequest) GetToken0() string {
	if x != nil {
		return x.Token0
	}
	return ""
}

func (x *GetPairRequest) GetToken1() string {
	if x != nil {
		return x.Token1
	}
	return ""
}

type GetPairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetPairResponse) Reset() {
	*x = GetPairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_whirlpool_whirlpool_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairResponse) ProtoMessage() {}

func (x *GetPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whirlpool_whirlpool_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairResponse.ProtoReflect.Descriptor instead.
func (*GetPairResponse) Descriptor() ([]byte, []int) {
	return file_proto_whirlpool_whirlpool_proto_rawDescGZIP(), []int{3}
}

func (x *GetPairResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PoolAddr string `protobuf:"bytes,1,opt,name=poolAddr,proto3" json:"poolAddr,omitempty"`
}

func (x *GetPoolRequest) Reset() {
	*x = GetPoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_whirlpool_whirlpool_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolRequest) ProtoMessage() {}

func (x *GetPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whirlpool_whirlpool_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolRequest.ProtoReflect.Descriptor instead.
func (*GetPoolRequest) Descriptor() ([]byte, []int) {
	return file_proto_whirlpool_whirlpool_proto_rawDescGZIP(), []int{4}
}

func (x *GetPoolRequest) GetPoolAddr() string {
	if x != nil {
		return x.PoolAddr
	}
	return ""
}

type GetPoolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fee int32 `protobuf:"varint,1,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (x *GetPoolResponse) Reset() {
	*x = GetPoolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_whirlpool_whirlpool_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolResponse) ProtoMessage() {}

func (x *GetPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whirlpool_whirlpool_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolResponse.ProtoReflect.Descriptor instead.
func (*GetPoolResponse) Descriptor() ([]byte, []int) {
	return file_proto_whirlpool_whirlpool_proto_rawDescGZIP(), []int{5}
}

func (x *GetPoolResponse) GetFee() int32 {
	if x != nil {
		return x.Fee
	}
	return 0
}

var File_proto_whirlpool_whirlpool_proto protoreflect.FileDescriptor

var file_proto_whirlpool_whirlpool_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x68, 0x69, 0x72, 0x6c, 0x70, 0x6f, 0x6f,
	0x6c, 0x2f, 0x77, 0x68, 0x69, 0x72, 0x6c, 0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x77, 0x68, 0x69, 0x72, 0x6c, 0x70, 0x6f, 0x6f, 0x6c, 0x22, 0x41, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x42, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x22,
	0x2c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x40, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x22,
	0x2b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6f, 0x6f, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x6f, 0x6f, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x22, 0x23, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x66, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x66, 0x65, 0x65, 0x32,
	0xda, 0x01, 0x0a, 0x09, 0x57, 0x68, 0x69, 0x72, 0x6c, 0x70, 0x6f, 0x6f, 0x6c, 0x12, 0x45, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x2e, 0x77, 0x68, 0x69, 0x72,
	0x6c, 0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x77, 0x68, 0x69, 0x72, 0x6c, 0x70, 0x6f, 0x6f,
	0x6c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x12,
	0x19, 0x2e, 0x77, 0x68, 0x69, 0x72, 0x6c, 0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x77, 0x68, 0x69,
	0x72, 0x6c, 0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50,
	0x6f, 0x6f, 0x6c, 0x12, 0x19, 0x2e, 0x77, 0x68, 0x69, 0x72, 0x6c, 0x70, 0x6f, 0x6f, 0x6c, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x77, 0x68, 0x69, 0x72, 0x6c, 0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f,
	0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x65, 0x6e, 0x36,
	0x30, 0x33, 0x34, 0x2f, 0x61, 0x72, 0x62, 0x69, 0x74, 0x72, 0x61, 0x67, 0x65, 0x2d, 0x62, 0x6f,
	0x74, 0x2f, 0x77, 0x68, 0x69, 0x72, 0x6c, 0x70, 0x6f, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_whirlpool_whirlpool_proto_rawDescOnce sync.Once
	file_proto_whirlpool_whirlpool_proto_rawDescData = file_proto_whirlpool_whirlpool_proto_rawDesc
)

func file_proto_whirlpool_whirlpool_proto_rawDescGZIP() []byte {
	file_proto_whirlpool_whirlpool_proto_rawDescOnce.Do(func() {
		file_proto_whirlpool_whirlpool_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_whirlpool_whirlpool_proto_rawDescData)
	})
	return file_proto_whirlpool_whirlpool_proto_rawDescData
}

var file_proto_whirlpool_whirlpool_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_whirlpool_whirlpool_proto_goTypes = []interface{}{
	(*GetPriceRequest)(nil),  // 0: whirlpool.GetPriceRequest
	(*GetPriceResponse)(nil), // 1: whirlpool.GetPriceResponse
	(*GetPairRequest)(nil),   // 2: whirlpool.GetPairRequest
	(*GetPairResponse)(nil),  // 3: whirlpool.GetPairResponse
	(*GetPoolRequest)(nil),   // 4: whirlpool.GetPoolRequest
	(*GetPoolResponse)(nil),  // 5: whirlpool.GetPoolResponse
}
var file_proto_whirlpool_whirlpool_proto_depIdxs = []int32{
	0, // 0: whirlpool.Whirlpool.GetPrice:input_type -> whirlpool.GetPriceRequest
	2, // 1: whirlpool.Whirlpool.GetPair:input_type -> whirlpool.GetPairRequest
	4, // 2: whirlpool.Whirlpool.GetPool:input_type -> whirlpool.GetPoolRequest
	1, // 3: whirlpool.Whirlpool.GetPrice:output_type -> whirlpool.GetPriceResponse
	3, // 4: whirlpool.Whirlpool.GetPair:output_type -> whirlpool.GetPairResponse
	5, // 5: whirlpool.Whirlpool.GetPool:output_type -> whirlpool.GetPoolResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_whirlpool_whirlpool_proto_init() }
func file_proto_whirlpool_whirlpool_proto_init() {
	if File_proto_whirlpool_whirlpool_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_whirlpool_whirlpool_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_whirlpool_whirlpool_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_whirlpool_whirlpool_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_whirlpool_whirlpool_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_whirlpool_whirlpool_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_whirlpool_whirlpool_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPoolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_whirlpool_whirlpool_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_whirlpool_whirlpool_proto_goTypes,
		DependencyIndexes: file_proto_whirlpool_whirlpool_proto_depIdxs,
		MessageInfos:      file_proto_whirlpool_whirlpool_proto_msgTypes,
	}.Build()
	File_proto_whirlpool_whirlpool_proto = out.File
	file_proto_whirlpool_whirlpool_proto_rawDesc = nil
	file_proto_whirlpool_whirlpool_proto_goTypes = nil
	file_proto_whirlpool_whirlpool_proto_depIdxs = nil
}
